repository: ml4rookies/ml4rookies.github.io

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Machine Learning for Rookies
# this appears on the top navigation bar next to the home button

site_title: Machine Learning for Rookies
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: ML Content Development Working Group
# this appears in the footer

github_editme_path: ml4rookies/ml4rookies.github.io
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: UA-37042823-6
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
# these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Machine Learning for Rookies

#feedback_email: tomjoht@gmail.com
# used as a contact email for the Feedback link in the top navigation bar

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: ml4rookies_sidebar
      topnav: topnav

sidebars:
- ml4rookies_sidebar

description: "Machine Learning for Rookies is an entry level document for junior developers with no/low knowledge of Python programming and machine learning."

github: [metadata]
